version: '3'

services:
  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: marcos012/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: marcos012/nginx:prod
    container_name: ginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge